import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';
import { Shield, CheckCircle, AlertTriangle, Download, Share2, Star, ArrowLeft } from 'lucide-react';
import { formSubmission } from '../lib/supabase';
import { downloadCalculatorPDF, shareCalculatorResult } from '../lib/html2pdfGenerator';
import ShareResultBanner from '../components/ShareResultBanner';

export default function ComplianceRiskChecker() {
  const [answers, setAnswers] = useState({});
  const [companyInfo, setCompanyInfo] = useState({
    name: '',
    industry: '',
    employees: '',
    email: ''
  });
  const [showResult, setShowResult] = useState(false);
  const [result, setResult] = useState(null);
  const [crmError, setCrmError] = useState(false);
  const [downloaded, setDownloaded] = useState(false);
  const [shared, setShared] = useState(false);
  const [copied, setCopied] = useState(false);

  const questions = [
    'Do you have updated employment contracts for all employees?',
    'Are you compliant with minimum wage requirements?',
    'Do you maintain proper working hours records?',
    'Are you filing TDS returns on time?',
    'Do you have workplace safety policies?',
    'Do you have a privacy policy in place?',
    'Are you conducting regular safety audits?',
    'Do you have anti-discrimination policies?',
    'Are you maintaining statutory registers?',
    'Do you have grievance redressal mechanisms?'
  ];

  const handleAnswer = (index, answer) => {
    setAnswers(prev => ({
      ...prev,
      [index]: answer
    }));
  };

  const handleCompanyInfoChange = (field, value) => {
    setCompanyInfo(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const calculateScore = () => {
    const answeredYes = Object.values(answers).filter(answer => answer === 'yes').length;
    return Math.round((answeredYes / questions.length) * 100);
  };

  const getRiskLevel = (score) => {
    if (score >= 90) return { level: 'Low Risk', color: 'text-green-600', bgColor: 'bg-green-50' };
    if (score >= 70) return { level: 'Moderate Risk', color: 'text-yellow-600', bgColor: 'bg-yellow-50' };
    if (score >= 50) return { level: 'High Risk', color: 'text-orange-600', bgColor: 'bg-orange-50' };
    return { level: 'Critical Risk', color: 'text-red-600', bgColor: 'bg-red-50' };
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    const score = calculateScore();
    const riskLevel = getRiskLevel(score);

    const resultData = {
      score,
      riskLevel: riskLevel.level,
      companyInfo,
      date: new Date().toLocaleDateString()
    };

    setResult(resultData);
    setShowResult(true);

    if (companyInfo.email) {
      const ok = await addContactToHubSpot({ 
        email: companyInfo.email,
        name: companyInfo.name,
        company: companyInfo.name
      });
      if (!ok) setCrmError(true);
    }
  };

  const handleDownload = async () => {
    if (!result) return;
    
    try {
      const filename = await downloadCalculatorPDF('compliance-risk-checker', result, companyInfo);
      setDownloaded(true);
      setTimeout(() => setDownloaded(false), 3000);
    } catch (error) {
      console.error('PDF generation failed:', error);
      // Fallback to old TXT method
      const report = `Compliance Risk Assessment Report
==========================================

Company: ${result.companyInfo.name}
Industry: ${result.companyInfo.industry}
Employees: ${result.companyInfo.employees}
Assessment Date: ${result.date}

COMPLIANCE SCORE: ${result.score}%
RISK LEVEL: ${result.riskLevel}

Generated by: Hire With Prachi
Professional HR Solutions & Consulting
    `;

      const blob = new Blob([report], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `compliance-assessment-${result.companyInfo.name.toLowerCase().replace(/\s+/g, '-')}.txt`;
      a.click();
      URL.revokeObjectURL(url);
      setDownloaded(true);
    }
  };

  const handleShare = async (shareText) => {
    try {
      if (navigator.share) {
        await navigator.share({
          title: 'Compliance Risk Assessment Results',
          text: shareText,
          url: window.location.href
        });
      } else {
        await navigator.clipboard.writeText(shareText);
      }
      setShared(true);
      setTimeout(() => setShared(false), 3000);
    } catch (error) {
      console.log('Share failed:', error);
    }
  };

  const handleCopy = async (shareText) => {
    try {
      await navigator.clipboard.writeText(shareText);
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    } catch (error) {
      console.log('Copy failed:', error);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-red-50 via-orange-50 to-yellow-100">
      <Helmet>
        <title>Compliance Risk Checker 2025 | HR Compliance Assessment - Prachi</title>
        <meta name="description" content="Assess your HR compliance status and identify potential risks with our comprehensive compliance risk checker." />
      </Helmet>

      {/* Header */}
      <header className="bg-white shadow-lg border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <div className="bg-gradient-to-r from-red-600 to-pink-600 p-2 rounded-lg">
                <Shield className="h-8 w-8 text-white" />
              </div>
              <div>
                <h1 className="text-2xl font-bold text-gray-900">Prachi HR Solutions</h1>
                <p className="text-sm text-gray-600">Compliance Risk Checker</p>
              </div>
            </div>
            <div className="hidden md:flex items-center space-x-6">
              <div className="flex items-center space-x-2 text-gray-600">
                <Star className="h-4 w-4 text-yellow-500" />
                <span className="text-sm">4.9/5 Rating</span>
              </div>
            </div>
          </div>
        </div>
      </header>

      {/* Navigation */}
      <nav className="bg-white shadow-sm border-b border-gray-100">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <Link 
                to="/"
                className="flex items-center space-x-2 text-gray-600 hover:text-gray-900 transition-colors"
              >
                <ArrowLeft className="h-4 w-4" />
                <span>Back to Home</span>
              </Link>
            </div>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="py-12 px-4 text-center">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4 leading-tight">
            Compliance Risk Checker 2025
          </h1>
          <p className="text-xl text-gray-600 mb-8 leading-relaxed">
            Assess your HR compliance status and identify potential risks with our comprehensive compliance checker
          </p>
          <div className="flex flex-wrap justify-center gap-4 mb-8">
            <div className="flex items-center space-x-2 bg-white px-4 py-2 rounded-full shadow-md">
              <CheckCircle className="h-5 w-5 text-green-500" />
              <span className="text-sm font-medium">100% Free</span>
            </div>
            <div className="flex items-center space-x-2 bg-white px-4 py-2 rounded-full shadow-md">
              <Shield className="h-5 w-5 text-blue-500" />
              <span className="text-sm font-medium">Secure & Private</span>
            </div>
          </div>
        </div>
      </section>

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-12">
        <div className="grid lg:grid-cols-3 gap-8">
          {/* Assessment Form */}
          <div className="lg:col-span-2">
            <div className="bg-white rounded-2xl shadow-xl border border-gray-200 overflow-hidden">
              <div className="bg-gradient-to-r from-red-600 to-pink-600 px-6 py-4">
                <h2 className="text-2xl font-bold text-white flex items-center space-x-2">
                  <Shield className="h-6 w-6" />
                  <span>Compliance Risk Assessment</span>
                </h2>
                <p className="text-red-100 mt-1">Complete the assessment to identify compliance risks</p>
              </div>

              <div className="p-6">
                {!showResult ? (
                  <form onSubmit={handleSubmit} className="space-y-6">
                    {/* Company Information */}
                    <div className="space-y-4">
                      <h3 className="text-lg font-semibold text-gray-900 border-b border-gray-200 pb-2">
                        Company Information
                      </h3>
                      <div className="grid md:grid-cols-2 gap-4">
                        <div>
                          <label className="block text-sm font-semibold text-gray-700 mb-2">
                            Company Name *
                          </label>
                          <input 
                            type="text" 
                            value={companyInfo.name} 
                            onChange={(e) => handleCompanyInfoChange('name', e.target.value)} 
                            className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500 focus:border-transparent" 
                            required 
                          />
                        </div>
                        <div>
                          <label className="block text-sm font-semibold text-gray-700 mb-2">
                            Industry *
                          </label>
                          <select 
                            value={companyInfo.industry} 
                            onChange={(e) => handleCompanyInfoChange('industry', e.target.value)} 
                            className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500 focus:border-transparent"
                            required
                          >
                            <option value="">Select Industry</option>
                            <option value="Technology">Technology</option>
                            <option value="Manufacturing">Manufacturing</option>
                            <option value="Healthcare">Healthcare</option>
                            <option value="Retail">Retail</option>
                            <option value="Other">Other</option>
                          </select>
                        </div>
                        <div>
                          <label className="block text-sm font-semibold text-gray-700 mb-2">
                            Number of Employees *
                          </label>
                          <input 
                            type="number" 
                            min="1" 
                            value={companyInfo.employees} 
                            onChange={(e) => handleCompanyInfoChange('employees', e.target.value)} 
                            className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500 focus:border-transparent" 
                            required 
                          />
                        </div>
                        <div>
                          <label className="block text-sm font-semibold text-gray-700 mb-2">
                            Email Address *
                          </label>
                          <input 
                            type="email" 
                            value={companyInfo.email} 
                            onChange={(e) => handleCompanyInfoChange('email', e.target.value)} 
                            className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500 focus:border-transparent" 
                            required 
                          />
                        </div>
                      </div>
                    </div>

                    {/* Compliance Questions */}
                    <div className="space-y-4">
                      <h3 className="text-lg font-semibold text-gray-900 border-b border-gray-200 pb-2">
                        Compliance Assessment Questions
                      </h3>
                      <div className="space-y-4">
                        {questions.map((question, index) => (
                          <div key={index} className="bg-gray-50 p-4 rounded-lg">
                            <p className="text-sm font-medium text-gray-900 mb-3">
                              {index + 1}. {question}
                            </p>
                            <div className="flex space-x-4">
                              <label className="flex items-center space-x-2 cursor-pointer">
                                <input 
                                  type="radio" 
                                  name={`question_${index}`} 
                                  value="yes" 
                                  checked={answers[index] === 'yes'} 
                                  onChange={() => handleAnswer(index, 'yes')} 
                                  className="text-red-600 focus:ring-red-500" 
                                />
                                <span className="text-sm text-gray-700">Yes</span>
                              </label>
                              <label className="flex items-center space-x-2 cursor-pointer">
                                <input 
                                  type="radio" 
                                  name={`question_${index}`} 
                                  value="no" 
                                  checked={answers[index] === 'no'} 
                                  onChange={() => handleAnswer(index, 'no')} 
                                  className="text-red-600 focus:ring-red-500" 
                                />
                                <span className="text-sm text-gray-700">No</span>
                              </label>
                            </div>
                          </div>
                        ))}
                      </div>

                      <button 
                        type="submit" 
                        className="w-full bg-gradient-to-r from-red-600 to-pink-600 text-white py-4 px-6 rounded-xl font-bold text-lg hover:from-red-700 hover:to-pink-700 transition-all duration-300 shadow-lg hover:shadow-xl"
                      >
                        Get Assessment Results
                      </button>
                    </div>
                  </form>
                ) : (
                  <div className="text-center py-8">
                    <CheckCircle className="h-16 w-16 text-green-500 mx-auto mb-4" />
                    <h3 className="text-xl font-bold text-gray-900 mb-2">Assessment Complete!</h3>
                    <p className="text-gray-600">Your compliance risk assessment results are ready.</p>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Results Section */}
          <div className="lg:col-span-1">
            {showResult && result ? (
              <div className="space-y-6">
                {/* Main Result */}
                <motion.div 
                  className="bg-white rounded-2xl shadow-xl border border-gray-200 p-6" 
                  initial={{ opacity: 0, y: 20 }} 
                  animate={{ opacity: 1, y: 0 }}
                >
                  <div className="text-center mb-6">
                    <div className="w-16 h-16 bg-gradient-to-r from-red-500 to-pink-500 rounded-2xl flex items-center justify-center mx-auto mb-4">
                      <Shield className="h-8 w-8 text-white" />
                    </div>
                    <h3 className="text-xl font-bold text-gray-900 mb-2">Compliance Score</h3>
                  </div>

                  <div className="space-y-4">
                    <div className="bg-green-50 rounded-xl p-4 text-center">
                      <div className="text-3xl font-bold text-green-700 mb-1">
                        {result.score}%
                      </div>
                      <div className="text-sm text-green-600">Compliance Score</div>
                    </div>

                    <div className={`rounded-lg p-3 ${getRiskLevel(result.score).bgColor}`}>
                      <p className={`text-sm font-semibold ${getRiskLevel(result.score).color}`}>
                        Risk Level: {getRiskLevel(result.score).level}
                      </p>
                    </div>

                    <div className="space-y-3">
                      <div className="flex justify-between items-center">
                        <span className="text-gray-600">Company:</span>
                        <span className="font-semibold">{result.companyInfo.name}</span>
                      </div>
                      <div className="flex justify-between items-center">
                        <span className="text-gray-600">Industry:</span>
                        <span className="font-semibold">{result.companyInfo.industry}</span>
                      </div>
                      <div className="flex justify-between items-center">
                        <span className="text-gray-600">Employees:</span>
                        <span className="font-semibold">{result.companyInfo.employees}</span>
                      </div>
                    </div>
                  </div>
                </motion.div>

                {/* Share Banner */}
                <ShareResultBanner
                  result={result}
                  calculatorType="Compliance Risk Checker"
                  onShare={handleShare}
                  onDownload={handleDownload}
                  onCopy={handleCopy}
                  isShared={shared}
                  isDownloaded={downloaded}
                  isCopied={copied}
                />
              </div>
            ) : (
              <div className="bg-white rounded-2xl shadow-xl border border-gray-200 p-6 sticky top-8">
                <div className="text-center">
                  <div className="w-16 h-16 bg-gray-100 rounded-2xl flex items-center justify-center mx-auto mb-4">
                    <Shield className="h-8 w-8 text-gray-400" />
                  </div>
                  <h3 className="text-xl font-bold text-gray-900 mb-2">Assess Your Compliance</h3>
                  <p className="text-gray-600 text-sm">
                    Complete the assessment to identify compliance risks and get recommendations.
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <div className="flex items-center justify-center space-x-2 mb-4">
              <Shield className="h-6 w-6 text-red-400" />
              <span className="text-xl font-bold">Prachi HR Solutions</span>
            </div>
            <p className="text-gray-400 text-sm">
              Leading HR solutions provider helping businesses ensure compliance and mitigate risks.
            </p>
            <div className="mt-8 pt-8 border-t border-gray-800">
              <p className="text-gray-400 text-sm">
                © 2025 Prachi HR Solutions. All rights reserved.
              </p>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
} 